### ISSUE TITLE
publish on npm

### ISSUE THREAD

**Issue by maboiteaspam** [alanshaw/md-tokenizer#1]
Hi,

Don t you want to publish this module on npm ?

I would like to work with it, but i m not so comfort to link the github repo.

How do you think ? Let me know, i really like this module

**Comment by alanshaw** [comment]
Hi @maboiteaspam I'm not sure why I didn't publish it yet. Possibly because I wasn't sure if the tokens were in a useful format for my [md-parser](https://github.com/alanshaw/md-parser) which I never got round to finishing (nested lists being a particular pain point). I'm not sure the "parsing" approach was right. Anyway, since it's useful for you I've published it on npm - https://www.npmjs.com/package/md-tokenizer enjoy :)

**Comment by maboiteaspam** [comment]
amazing : °) thanks again.
